# Generated by Django 5.2.4 on 2025-09-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='owner',
            field=models.ForeignKey(blank=True, default='123456', on_delete=django.db.models.deletion.CASCADE, to='bank.profile'),
        ),
    ]
