# Generated by Django 5.2.4 on 2025-11-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_password_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.profile'),
        ),
    ]
